'use client';

import { FileDown, FileText, Table, Presentation, Download } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from '@/components/toast';

const exports = [
  {
    title: 'Marketing Report',
    description: 'Executive summary, KPIs, recommendations, and next actions.',
    filename: 'marketing-report',
    icon: FileText,
  },
  {
    title: 'Campaign Plan',
    description: 'Campaign goals, channels, timeline, budget, and measurement plan.',
    filename: 'campaign-plan',
    icon: Presentation,
  },
  {
    title: 'Buyer Personas',
    description: 'Persona profiles, pain points, platforms, and content preferences.',
    filename: 'buyer-personas',
    icon: FileText,
  },
  {
    title: 'Analytics Snapshot',
    description: 'Revenue, ROI, CTR, CPC, CPA, engagement, and audience segments.',
    filename: 'analytics-snapshot',
    icon: Table,
  },
];

export default function ExportCenterPage() {
  const { showToast } = useToast();

  const download = (name: string, format: 'pdf' | 'docx' | 'csv') => {
    const title = name.replace(/-/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
    const rows = [
      ['Section', 'Details'],
      ['Generated By', 'MultiMax AI Growth Studio'],
      ['Report', title],
      ['Key Insight', 'Focus budget on the highest-converting channel and improve conversion assets.'],
      ['Recommendation', 'Run weekly creative tests, review ROI, and refresh content calendar.'],
      ['Next Best Action', 'Launch a 7-day optimization sprint with clear KPI ownership.'],
    ];

    const content = format === 'csv'
      ? rows.map((row) => row.map((cell) => `"${cell}"`).join(',')).join('\n')
      : `${title}\n\n${rows.map(([section, details]) => `${section}: ${details}`).join('\n\n')}`;

    const mime = format === 'csv'
      ? 'text/csv'
      : format === 'pdf'
        ? 'application/pdf'
        : 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';

    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${name}.${format}`;
    link.click();
    URL.revokeObjectURL(url);
    showToast('success', `${title} exported as ${format.toUpperCase()}`);
  };

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      <div>
        <h1 className="text-3xl font-bold flex items-center gap-2">
          <FileDown className="h-8 w-8 text-primary" />
          Export Center
        </h1>
        <p className="text-muted-foreground mt-2">
          Export reports, campaign plans, analytics, AI strategies, and buyer personas.
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        {exports.map((item) => (
          <Card key={item.filename}>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <item.icon className="h-5 w-5 text-primary" />
                {item.title}
              </CardTitle>
              <CardDescription>{item.description}</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-3 gap-2">
                {(['pdf', 'docx', 'csv'] as const).map((format) => (
                  <Button key={format} variant="outline" onClick={() => download(item.filename, format)}>
                    <Download className="mr-2 h-4 w-4" />
                    {format.toUpperCase()}
                  </Button>
                ))}
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
